#+TITLE: SeqGrapheR

SeqGrapheR is a program for vizualization and exploration of sequence based
graphs generated in RepeatExplorer output. More information about RepeatExplorer can be found
on http://repeatexplorer.org/

Introduction to SeqGrapheR can be found in [[https://github.com/kavonrtep/SeqGrapheR/blob/master/vignettes/SeqGrapheR.pdf][vignette]] (obsolete).

* Installation

SeqGrapheR requires program ggobi (http://www.ggobi.org/docs/) installed.

For full functionality, SeqGrapheR needs also the following programs installed:
- Staden (http://staden.sourceforge.net/)
- Dotter (https://www.sanger.ac.uk/science/tools/seqtools)
- legacy NCBI blast (ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/)

In Debian/Ubuntu based linux distributions, the above programs can be installed using:
#+BEGIN_SRC sh
sudo apt-get -y install ncbi-blast+-legacy acedb-other-dotter staden ggobi
#+END_SRC

R programming environment and some dependencies can be installed using:
#+begin_src sh
sudo apt-get -y install r-base libcurl4-openssl-dev libxml2-dev libgtk2.0-dev libssl-dev build-essential gfortran libblas-dev liblapack-dev
#+end_src

Installation requires R package =devtools= and Bioconductor package =Biostrings=.
Start R session in terminal and install R packages:
#+BEGIN_SRC R
# install devtools:
install.packages("devtools")
# install biostrings:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings")
library(devtools)
install_github("kavonrtep/SeqGrapheR")
#+END_SRC

Note the  installation of SeqGrapheR  fails because packages gWidgets, gWidgetsRGtk2 and rggobi are not supported by your R version, you can try to install these packages manually from archived packages:
#+begin_src R
install_version("gWidgets", version = "0.0-54.1", repos = "http://cran.us.r-project.org")
install_version("gWidgetsRGtk2", version = "0.0-86", repos = "http://cran.us.r-project.org")
install_version("rggobi", version = "2.1.22", repos = "http://cran.us.r-project.org")
#+end_src


** Alternative installation using Singularity container
This is the simplest way how to run SeqGrapheR. Singularity can be installed either from source (see installation guide https://sylabs.io/guides/latest/user-guide/) or it can be installed using conda:
#+begin_src bash
conda install -c conda-forge singularity=3.6.3
#+end_src

Tehn, run SeqGrapheR use command:
#+begin_src bash
singularity run shub://kavonrtep/SeqGrapheR
#+end_src
With the above command you can automatically access data in you home directory. If you need to work with data which are not located in your home  directory use command:
#+begin_src bash
singularity run -B /path_to_you_data_directory:/data shub://kavonrtep/SeqGrapheR
#+end_src
this way the local directory  =/path_to_you_data_directory= will be bind to directory =/data= in singularity container.


** Alternative installation using conda

R packages and dependencies can be installed using conda. 
#+begin_src bash
conda create -n seqgrapher -c petrnovak -c iuc -c conda-forge -c bioconda -c pkgw-forge r-seqgrapher
#+end_src>

activate =seqgrapher= environment using:

#+begin_src bash
conda activate seqgrapher
#+end_src>

programs =Staden= and =dotter= are not available in Anaconda repository and must
be installed from linux distrubution repository. In Debian/Ubuntu based linux
distributions, you can use command

#+begin_src 
sudo apt-get -y install acedb-other-dotter staden 
#+end_src



* How to run SeqGrapheR

In terminal window start =R= environment. In R session run:
#+BEGIN_SRC R
library(SeqGrapheR)
# start GUI:
SeqGrapheR()
#+END_SRC

