#+TITLE: SeqGrapheR

SeqGrapheR is a program for vizualization and exploration of sequence based
graphs generated in RepeatExplorer output. More information about RepeatExplorer can be found
on http://repeatexplorer.org/

Introduction to SeqGrapheR can be found in [[https://github.com/kavonrtep/SeqGrapheR/blob/master/vignettes/SeqGrapheR.pdf][vignette]] (obsolete).

* Installation

SeqGrapheR requires program ggobi (http://www.ggobi.org/docs/) installed.

For full functionality, SeqGrapheR needs also the following programs installed:
- Staden (http://staden.sourceforge.net/)
- Dotter (https://www.sanger.ac.uk/science/tools/seqtools)
- legacy NCBI blast (ftp://ftp.ncbi.nlm.nih.gov/blast/executables/legacy.NOTSUPPORTED/)

In Debian/Ubuntu based linux distributions, the above programs can be installed using:
#+BEGIN_SRC sh
sudo apt-get -y install ncbi-blast+-legacy acedb-other-dotter staden ggobi
#+END_SRC

R programming environment and some dependencies can be installed using:
#+begin_src sh
sudo apt-get -y install r-base libcurl4-openssl-dev libxml2-dev libgtk2.0-dev libssl-dev build-essential gfortran libblas-dev liblapack-dev
#+end_src

Installation requires R package =devtools= and Bioconductor package =Biostrings=.
Start R session in terminal and install R packages:
#+BEGIN_SRC R
# install devtools:
install.packages("devtools")
# install biostrings:
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("Biostrings")
library(devtools)
install_github("kavonrtep/SeqGrapheR")
#+END_SRC

Note the  installation of SeqGrapheR  fails because packages gWidgets, gWidgetsRGtk2 and rggobi are not supported by your R version, you can try to install these packages manually from archived packages:
#+begin_src R
install_version("gWidgets", version = "0.0-54.1", repos = "http://cran.us.r-project.org")
install_version("gWidgetsRGtk2", version = "0.0-86", repos = "http://cran.us.r-project.org")
install_version("rggobi", version = "2.1.22", repos = "http://cran.us.r-project.org")
#+end_src


** Alternative installation using Singularity container
This is the simplest way how to run SeqGrapheR. Singularity can be installed either from source (see installation guide https://sylabs.io/guides/latest/user-guide/) or it can be installed using conda:
#+begin_src bash
conda install -c conda-forge singularity=3.6.3
#+end_src

Then, run SeqGrapheR use command:
#+begin_src bash
singularity run shub://kavonrtep/SeqGrapheR
#+end_src
With the above command you can automatically access data in you home directory. If you need to work with data which are not located in your home  directory use the command:
#+begin_src bash
singularity run -B /path_to_you_data_directory:/data shub://kavonrtep/SeqGrapheR
#+end_src
this way the local directory  =/path_to_you_data_directory= will be bind to directory =/data= in singularity container.


** Alternative installation using conda

R packages and dependencies can be installed using conda. 
#+begin_src bash
conda create -n seqgrapher -c petrnovak -c iuc -c conda-forge -c bioconda -c pkgw-forge r-seqgrapher
#+end_src>

activate =seqgrapher= environment using:

#+begin_src bash
conda activate seqgrapher
#+end_src>

programs =Staden= and =dotter= are not available in Anaconda repository and must
be installed from linux distrubution repository. In Debian/Ubuntu based linux
distributions, you can use command

#+begin_src 
sudo apt-get -y install acedb-other-dotter staden 
#+end_src

** Alternative installation using Windows Subsystem for Linux (WSL)

Because SeqGrapheR has a graphical user interface you will probably need to set up xrdp to Remote Desktop onto the linux virtual machine.
There is a guide here to do that: https://dev.to/darksmile92/linux-on-windows-wsl-with-desktop-environment-via-rdp-522g

One of the comments from the link above suggests these steps. Open WSL and run:

#+begin_src bash
sudo apt-get install xrdp
sudo apt-get install xfce4
sudo apt-get install xfce4-goodies
sudo cp /etc/xrdp/xrdp.ini /etc/xrdp/xrdp.ini.bak
sudo sed -i 's/3389/3390/g' /etc/xrdp/xrdp.ini
sudo sed -i 's/max_bpp=32/#max_bpp=32\nmax_bpp=128/g' /etc/xrdp/xrdp.ini
sudo sed -i 's/xserverbpp=24/#xserverbpp=24\nxserverbpp=128/g' /etc/xrdp/xrdp.ini
echo xfce4-session > ~/.xsession
#+end_src

You'll then need to edit the /// file. You can use any command-line editor to do this, e.g. nano.
#+begin_src bash
sudo nano /etc/xrdp/startwm.sh
#+end_src

Comment out these lines:

#+begin_src
#test -x /etc/X11/Xsession && exec /etc/X11/Xsession
#exec /bin/sh /etc/X11/Xsession
#+end_src

And add these lines to the bottom of the file: 
#+begin_src
# xfce
startxfce4
#+end_src

Once that's set up you should be able to run the command below and use Remote Desktop to connect to your virtual machine.

#+begin_src bash
sudo /etc/init.d/xrdp start
#+end_src

Remote Desktop to th virtual machine (localhost:3390) and open a terminal.
Before you can continue with the install you'll need to check if the PKG_CONFIG_PATH environment variable is set. If not, set it to "usr/lib/pkgconfig".

#+begin_src bash
echo $PKG_CONFIG_PATH
export PKG_CONFIG_PATH=/usr/lib/pkgconfig
#+end_src

When you launch R you can check if this environment variable is set correctly with the following line:
#+begin_src
Sys.getenv("PKG_CONFIG_PATH")
#+end_src

NOTE: If running R with the sudo command you'll want to use the -E option to preserve environment variables.

The following commands will get SeqGrapheR up and running:

#+begin_src bash
sudo apt-get -y install r-base ncbi-blast+-legacy acedb-other-dotter staden ggobi libcurl4-openssl-dev libxml2-dev libgtk2.0-dev libssl-dev build-essential gfortran libblas-dev liblapack-dev

sudo -E R
Sys.getenv("PKG_CONFIG_PATH")
install.packages("devtools")
install.packages("BiocManager")
BiocManager::install("Biostrings")
library(devtools)
install_version("gWidgets", version = "0.0-54.1", repos = "http://cran.us.r-project.org")
install_version("gWidgetsRGtk2", version = "0.0-86", repos = "http://cran.us.r-project.org")
install_version("rggobi", version = "2.1.22", repos = "http://cran.us.r-project.org")
install_github("kavonrtep/SeqGrapheR")
SeqGrapheR()
#+end_src

* How to run SeqGrapheR

In terminal window start =R= environment. In R session run:
#+BEGIN_SRC R
library(SeqGrapheR)
# start GUI:
SeqGrapheR()
#+END_SRC

